CREATE TABLE vehicles (
    kundennummer/filiale text,
    interne_nummer text,
    kategorie text,
    marke text,
    modell text,
    leistung integer,
    hu date,
    ez date,
    kilometer integer,
    preis text,
    mwst integer,
    oldtimer boolean,
    vin text,
    beschaedigtes_fahrzeug boolean,
    farbe text,
    klima integer,
    taxi boolean,
    behindertengerecht boolean,
    jahreswagen boolean,
    neufahrzeug boolean,
    unsere empfehlung boolean,
    haendlerpreis text,
    bemerkung text,
    bild_id text,
    metallic boolean,
    waehrung text,
    mwstsatz text,
    garantie integer,
    leichtmetallfelgen boolean,
    esp boolean,
    abs boolean,
    Anhängerkupplung boolean,
    wegfahrsperre boolean,
    navigationssystem boolean,
    schiebedach boolean,
    zentralverriegelung boolean,
    fensterheber boolean,
    allradantrieb boolean,
    tueren integer,
    umweltplakette integer,
    servolenkung boolean,
    biodiesel boolean,
    scheckheftgepflegt boolean,
    katalysator boolean,
    kickstarter boolean,
    estarter boolean,
    vorfuehrfahrzeug boolean,
    antrieb integer,
    ccm integer,
    tragkraft integer,
    nutzlast integer,
    gesamtgewicht integer,
    hubhoehe integer,
    bauhoehe integer,
    baujahr integer,
    betriebsstunden integer,
    sitze text,
    schadstoff integer,
    kabinenart integer,
    achsen integer,
    tempomat boolean,
    standheizung boolean,
    kabine boolean,
    schutzdach boolean,
    vollverkleidung boolean,
    komunal boolean,
    kran boolean,
    retarder_intarder boolean,
    schlafplatz boolean,
    tv boolean,
    wc boolean,
    ladebordwand boolean,
    hydraulikanlage text,
    schiebetuer boolean,
    radformel integer,
    trennwand boolean,
    ebs boolean,
    vermietbar boolean,
    kompressor boolean,
    luftfederung boolean,
    scheibenbremse boolean,
    fronthydraulik boolean,
    bss boolean,
    schnellwechsel boolean,
    zsa boolean,
    kueche boolean,
    kuehlbox boolean,
    schlafsitze boolean,
    frontheber boolean,
    sichtbar_nur_fuer_Haendler boolean,
    reserviert boolean,
    envkv boolean,
    verbrauch_innerorts numeric,
    verbrauch_ausserorts numeric,
    verbrauch_kombiniert numeric,
    emission integer,
    xenonscheinwerfer boolean,
    sitzheizung boolean,
    partikelfilter boolean,
    einparkhilfe boolean,
    schwackecode integer,
    lieferdatum date,
    lieferfrist text,
    ueberfuehrungskosten integer,
    hu/au_neu boolean,
    kraftstoffart integer,
    getriebeart integer,
    exportfahrzeug boolean,
    tageszulassung boolean,
    blickfaenger boolean,
    hsn text,
    tsn text,
    seite_1_inserat boolean,
    e10 boolean,
    qualitaetssiegel text,
    pflanzenoel boolean,
    scr boolean,
    koffer boolean,
    sturzbuegel boolean,
    scheibe boolean,
    standklima boolean,
    s-s-bereifung boolean,
    strassenzulassung boolean,
    etagenbett boolean,
    festbett boolean,
    heckgarage boolean,
    markise boolean,
    sep-dusche boolean,
    solaranlage boolean,
    mittelsitzgruppe boolean,
    rundsitzgruppe boolean,
    seitensitzgruppe boolean,
    hagelschaden boolean,
    schlafplaetze integer,
    fahrzeuglaenge integer,
    fahrzeugbreite integer,
    fahrzeughoehe integer,
    laderaum-europalette integer,
    laderaum-volumen integer,
    laderaum-laenge integer,
    laderaum-breite integer,
    laderaum-hoehe integer,
    inserat als 'neu' markieren boolean,
    effektiver jahreszins text,
    monatliche rate text,
    laufzeit text,
    anzahlung integer,
    schlussrate integer,
    finanzierungsfeature boolean,
    interieurfarbe integer,
    interieurtyp integer,
    airbag text,
    vorbesitzer integer,
    top inserat boolean,
    bruttokreditbetrag text,
    abschlussgebuehren text,
    ratenabsicherung text,
    nettokreditbetrag text,
    anbieterbank text,
    soll-zinssatz text,
    art des soll-zinssatzes text,
    landesversion text,
    video-url text,
    energieeffizienzklasse text,
    envkv_benzin_sorte text,
    elektrische seitenspiegel boolean,
    sportfahrwerk boolean,
    sportpaket boolean,
    bluetooth boolean,
    bordcomputer boolean,
    cd spieler boolean,
    elektrische sitzeinstellung boolean,
    head-up display boolean,
    freisprecheinrichtung boolean,
    mp3 schnittstelle boolean,
    multifunktionslenkrad boolean,
    skisack boolean,
    tuner oder radio boolean,
    sportsitze boolean,
    panorama dach boolean,
    kindersitzbefestigung (ISOFIX) boolean,
    kurvenlicht boolean,
    lichtsensor boolean,
    nebelscheinwerfer boolean,
    tagfahrlicht boolean,
    traktionskontrolle boolean,
    start stop automatik boolean,
    regensensor boolean,
    nichtraucher fahrzeug boolean,
    dachreling boolean,
    unfallfahrzeug boolean,
    fahrtauglich boolean,
    produktionsdatum date,
    einparkhilfe sensoren vorne boolean,
    einparkhilfe sensoren hinten boolean,
    einparkhilfe kamera boolean,
    einparkhilfe selbstlenkendes system boolean,
    rotstiftpreis integer,
    ebayk export integer,
    plugin hybrid boolean,
    kombinierter stromverbrauch text,
    highlight 1 text,
    highlight 2 text,
    highlight 3 text,
    bedingungen finanzierungsvorschlag text,
    scheinwerferreinigungsanlage boolean,
    fernlichtassistent boolean,
    ambientes licht boolean,
    sitzheizung hinten boolean,
    elektrische sitzeinstellung hinten boolean,
    raucherpaket boolean,
    umklappbarer beifahrersitz boolean,
    volldigitales kombiinstrument boolean,
    winterpaket boolean,
    android auto boolean,
    apple carplay boolean,
    induktionsladen smartphones boolean,
    musikstreaming integriert boolean,
    w-lan boolean,
    reifen-allwetterreifen boolean,
    reifen-sommerreifen boolean,
    reifen-winterreifen boolean,
    notrad boolean,
    pannenkitt boolean,
    reserverad boolean,
    stahlfelge boolean,
    e-fahrzeug-batterie-fehlt boolean,
    e-fahrzeug-batterie-gekauft boolean,
    e-fahrzeug-batterie-gemietet boolean,
    range extender boolean,
    isofix beifahrer boolean,
    gepäckraumabtrennung boolean,
    anhängerkupplung schwenkbar boolean,
    anhängerkupplung abnehmbar boolean,
    anhängerkupplung starr boolean,
    schiebetür rechts boolean,
    schiebetür links boolean,
    schiebetür beidseitig boolean,
    bi-xenon-licht boolean,
    laserlicht-scheinwerfer boolean,
    alarmanlage boolean,
    beheizbares lenkrad boolean,
    innenspiegel automatisch abbl. boolean,
    spurhalteassistent boolean,
    abstandstempomat boolean,
    led-scheinwerfer boolean,
    notbremsassistent boolean,
    abstandswarner boolean,
    spurwechselassistent boolean,
    sitzbelüftung boolean,
    mittelarmlehne boolean,
    beheizbare frontscheibe boolean,
    berganfahrassistent boolean,
    dab-radio boolean,
    elektrische heckklappe boolean,
    led-tagfahrlicht boolean,
    lederlenkrad boolean,
    lordosenstütze boolean,
    luftfederung boolean,
    massagesitz boolean,
    müdigkeitswarnsystem boolean,
    nachtsicht-assistent boolean,
    notrufsystem boolean,
    reifendruckkontrollsystem boolean,
    schaltwippen boolean,
    schiebetür boolean,
    soundsystem boolean,
    sprachsteuerung boolean,
    touchscreen boolean,
    usb boolean,
    verkehrszeichenerkennung boolean,
    schlüssellose zentralverriegelung boolean,
    klimaautomatik 2 zonen boolean,
    klimaautomatik 3 zonen boolean,
    klimaautomatik 4 zonen boolean,
    einparkhilfe kamera 360 boolean,
    blendfreies fernlicht (matrix) boolean,
    dienstwagen boolean,
    ehem. preisempfehlung uvp text,
    ausstattungslinie text,
    bauart text,
    hereinnahmedatum date,
    mobile.de Turboinserat boolean,
    effektiver jahreszins text,
    monatliche rate integer,
    laufzeit text,
    anzahlung integer,
    schlussrate integer,
    zielgruppe text,
    laufleistung integer,
    leasing restwert text,
    leasing mehrkilometer text,
    leasing minderkilometer text,
    anbieterbank text,
    soll-zinssatz text,
    art des soll-zinssatzes text,
    bedingungen leasingvorschlag text,
    leasinggesamtbetrag text,
    nettokreditbetrag text,
    schadstoffklassedetail text,
    geschwindigkeitsbegrenzungsanlage boolean,
    ekpreis text,
    instandsetzungskosten text,
    mobile.de klicks text,
    co2 emission wltp integer,
    leads offen integer,
    leads offen bearbeiter text,
    leads offen aktuell date,
    Lagerplatz text,
    Modellbasis text,
    Modelltext (erweitert) text,
    wltp kraftstoff kombiniert numeric,
    Leergewicht integer,
    Kennzeichen text,
    TwinnerWidget text,
    Leasing Restwertabschlag text,
    Modellschlüssel text,
    laufleistung (Finanzierung) integer,
    mietfahrzeug (aktiv) boolean,
    datum letzter großer kundendienst date,
    km-Stand letzter großer kundendienst integer,
    datum letzter (kleiner) kundendienst date,
    km-Stand letzter (kleiner) kundendienst integer,
    datum letzter ölwechsel date,
    km-Stand letzter ölwechsel integer,
    datum letzter bremsenwechsel date,
    km-Stand letzter bremsenwechsel integer,
    wltp kraftstoff innenstadt numeric,
    wltp kraftstoff stadtrand numeric,
    wltp kraftstoff landstrasse numeric,
    wltp kraftstoff autobahn numeric,
    kundenauftrag boolean,
    vorlauf boolean,
    kurvenlicht adaptiv boolean,
    aktionscode text,
    schwacke wenr. text,
    dat sd3 aktennummer text,
    leasing sonderkonditionen text,
    ueberfuhrung enthalten boolean,
    zulassung enthalten boolean,
    kfzlieferung enthalten boolean,
    wartung enthalten boolean,
    verschleiss enthalten boolean,
    garantieende datum date,
    auslieferung datum date,
    leasingmatrix text,
    kampagnenident text,
    Wartung pro Monat text,
    Verschleiß pro Monat text,
    Wartung & Verschleiß in Kombination pro Monat text,
    Haftplficht pro Monat text,
    Haftpflicht SB text,
    Vollkasko pro Monat text,
    Vollkasko SB text,
    KFZ-Lieferung einmalig text,
    KFZ-Steuer pro Monat in EUR text,
    8-fach Bereifung pro Monat in EUR text,
    TÜV (HU+AU) pro Monat in EUR text,
    Rückgabeversicherung pro Monat in EUR text,
    Zulassungskosten einmalig text,
    klimaautomatik 5 zonen boolean,
    Bafa Bonus (Umweltbonus Leasingmarkt) integer,
    Zylinder integer,
    Modelljahr integer,
    Auktionsfahrzeug boolean,
    Vorbesitzername text,
    Twinner 360Grad URL text,
    Versionsschlüssel text,
    Grundfarbe aussen text,
    Heckantrieb boolean,
    Frontantrieb boolean,
    Anzahl Gänge integer,
    Lenkrad höhenverstellbar boolean,
    Kilometerstand für Börsen integer,
    Aussenspiegel autom. abblendend boolean,
    Bonus berechtigt boolean,
    kombinierter stromverbrauch wltp text,
    Vornutzung integer,
    DAT Europa Code text,
    Handelsname Lieferant text,
    Reifentypkennung text,
    Reifenbezeichnung text,
    Tragfähigkeitsindex integer,
    Geschwindigkeitsindex text,
    Kraftstoffeffklasse text,
    Nasshaftungsklasse text,
    Externe Rollgeräuschklasse text,
    Wert externe Rollgeräusch integer,
    reserviert, muss leer sein text,
    Extreme Schneeverhältnis geeignet boolean,
    Eisreifen boolean,
    Herstellungsbeginn Reifentyp date,
    Herstellungsende Reifentyp date,
    Handelsname text,
    Reifenzusatzinfo text,
    Ladeleistung AC integer,
    Ladeleistung DC integer,
    EU-Reifenregisternummer (vorne) text,
    Fahrzeug im PKA ignorieren boolean,
    Schlüsselbrettnummer text,
    Teil-Ledscheinwerfer boolean,
    Garantie Monate integer,
    Komfortsitz boolean,
    Keramikbremse boolean,
    Sicherheitsintegralsitze boolean,
    Akustikverglasung boolean,
    Elek. Parkbremse boolean,
    Fahrersitz Höhenverstellbar boolean,
    Rückbank get.umleg. boolean,
    Softclose boolean,
    Bremsbelaganzeige boolean,
    Audio-Aux-Anschluss boolean,
    iPad/iPod-Anschluss boolean,
    Uhr&Drehzahlm. boolean,
    Allradlenkung boolean,
    Außenspiegel el. anklap. boolean,
    Außenspiegel beheizbar boolean,
    Außenspiegel abblend. boolean,
    Dachträger boolean,
    Optikschwarz boolean,
    Privacy Verglasung boolean,
    Sportabgasanlage boolean,
    Wärmeschutzglas boolean,
    AktivKopfstütze integer,
    autonomes Fahren integer,
    Modellreihe text,
    Finanzierungsprodukt text,
    Leasingprodukt text,
    Motorleistung (max) integer,
    Batteriespannung integer,
    Batteriekapazität integer,
    Batteriebauart integer,
    Quickdrop-System boolean,
    Standardladung integer,
    Ladedauer bei Standardladung (AC) (Wallbox/Ladestation) text,
    Schnellladung integer,
    Ladedauer bei Schnellladung (DC) (Wallbox/Ladestation) text,
    Elektromotor-Reichweite nach WLTP text,
    Elektromotor-Reichweite innerorts nach WLTP text,
    Gesamtreichweite nach WLTP text,
    Gesamtreichweite innerorts nach WLTP text,
    MobileAD-ID integer,
    Gewichtete kombinierte CO2-Emissionen WLTP integer,
    Gewichteter kombinierter Stromverbrauch WLTP text,
    Gewichteter kombinierter Kraftstoffverbrauch WLTP numeric,
    Mängelhinweis/Unfallinfo text,
    Hinweis Leasingangebot text,
    Hinweis Finanzierungsangebot text,
    EU-Reifenregisternummer (hinten) text,
    Homepage Exklusiv boolean,
    Youngtimer boolean,
    abo standort text,
    abo mindestalter in jahre integer,
    abo selbstbeteiligung integer,
    abo kaution integer,
    abo vertragsbedingungen text,
    abo mehrkm integer,
    abo verfuegbarkeit integer,
    abo lieferdatum date,
    abo lieferfrist in tagen integer,
    abo lieferoptionen text,
    abo lieferkosten integer,
    abo lieferkosten matrix text,
    abo bemerkung text,
    abo highlight text,
    abo toptags text,
    abo zahlungsbedingungen integer,
    abo rate integer,
    abo rate matrix text,
    abo startgebuehr integer,
    abo teaser detailpage text,
    interner identifier text,
    freigabe internetveröffentlichung integer,
    anzahl bilder integer,
    wärmepumpe boolean,
    einkäufer text,
    interne informationen text,
    onlinekauf boolean,
    co2-klasse (wltp) text,
    co2-Klasse (wltp) gewichtet, kombiniert text,
    co2-klasse (wltp) bei entladener Batterie text,
    co2-emissionen (wltp) bei entladener batterie integer,
    kombinierter kraftstoffverbrauch (wltp) entl. batterie numeric,
    state of health (soh) in % (batteriezustand) text,
    musterfahrzeug / virtuelles fahrzeug boolean,
    stromverbrauch innenstadt wltp text,
    stromverbrauch stadtrand wltp text,
    stromverbrauch landstrasse wltp text,
    stromverbrauch autobahn wltp text,
    verbrauch entladener batterie innenstadt wltp numeric,
    verbrauch entladener batterie stadtrand wltp numeric,
    verbrauch entladener batterie landstrasse wltp numeric,
    verbrauch entladener batterie autobahn wltp numeric,
    link pkwlabel text,
    mittlerer co2 preis pro t numeric,
    mittlerer co2 preis akkumuliert numeric,
    niedriger co2 preis pro t numeric,
    niedriger co2 preis akkumuliert numeric,
    hoher co2 preis pro tonne numeric,
    hoher co2 preis akkumuliert numeric,
    kraftstoffpreis (referenz) numeric,
    strompreis numeric,
    jahr der energiekosten bei 15.000 km jahresfahrleistung integer,
    energiekosten bei 15.000 km jahresfahrleistung numeric,
    kfzsteuer p.a. numeric,
    zeitrahmen (von) co2 kosten integer,
    zeitrahmen (bis) co2 kosten integer,
    URL KFZ-Detailseite text,
    KFZ-Ansprechpartner Email text,
    Letzte Wartung Datum date,
    Letzte Wartung KM integer,
    Anhängelast gebremst integer,
    Anhängelast ungebremst integer,
    Stützlast AHK integer,
    Tankgröße integer,
    Batteriezertifikat vorhanden boolean,
    Virtuelle Seitenspiegel boolean,
    Service neu boolean,
    Navigationsvorbereitung boolean,
    Farbe matt boolean,
    Rechtslenker boolean,
    Bidirektionales Laden boolean,
    Faltdach boolean,
    Elektr. Sitzeinstellung Memory-Funktion integer,
    Ausparkassistent boolean,
    Adaptives Fahrwerk boolean,
    Anhängerrangierassistent boolean,
    Vorbereitung Anhängerkupplung boolean,
    Sitzhöhe (Motorrad) integer,
    Reichweite (Motorrad) integer,
    Stoppie-Control (Motorrad) boolean,
    Wheelie-Control (Motorrad) boolean,
    Kurven-ABS (Motorrad) boolean,
    Schaltautomat (Motorrad) boolean,
    Blipper (Motorrad) boolean,
    Griffheizung (Motorrad) boolean,
    Semi-aktives Fahrwerk (Motorrad) boolean,
    Drossel (Motorrad) boolean,
    Stehhöhe (Wohnmobile) integer,
    SAT-Anlage (Wohnmobile) boolean,
    Fahrradträger (Wohnmobile) boolean,
    Rangierhilfe (Wohnmobile) boolean,
    Warmwasser (Wohnmobile) boolean,
    Queensize Bett (Wohnmobile) boolean,
    Französisches Bett (Wohnmobile) boolean,
    Einzelbett (Wohnmobile) boolean,
    Doppelbett hinten (Wohnmobile) boolean,
    Doppelbett vorne (Wohnmobile) boolean,
    Hubbetten (Klapp) (Wohnmobile) boolean,
    Aufstelldach-Doppelbett (Wohnmobile) boolean,
    Sitz Umbaubett (Wohnmobile) boolean,
    Sitzgruppe L-Form (Wohnmobile) boolean,
    Sitzgruppe Bar Form (Wohnmobile) boolean,
    Heizung Gas (Wohnmobile) boolean,
    Heizung Diesel (Wohnmobile) boolean,
    Heizung Benzin (Wohnmobile) boolean,
    Heizung Strom (Wohnmobile) boolean,
    Heizung Holz (Wohnmobile) boolean,
    Länge Typ (NFZ) text,
    Höhe Typ (NFZ) text,
    Radstand (Typ) text,
    Lenkachse boolean,
    Betriebsgewicht integer,
    Colorverglasung boolean,
    Nackenheizung (AIRSCARF) boolean,
    Tuning boolean,
    Waschwasserstandsanzeige boolean,
    Windschott (Cabrio) boolean,
    Zentralverriegelung mit Funk boolean,
    Batterieladung Steckertyp integer,
    Batterie-Garantie integer,
    Felgengröße integer,
    Zulässiges Gesamtgewicht integer,
    Radstand integer,
    Differentialsperre boolean,
    Beifahrer-Doppelsitz boolean,
    Holzboden boolean,
    Drehschemel boolean,
    Hochlader boolean,
    Innenverkleidung boolean,
    Ladeboden - Variabel boolean,
    Ladedruck & Temperaturanzeigen boolean,
    Zusatzscheinwerfer boolean,
    Seilwinde boolean,
    Tachograf boolean,
    Verkleidung boolean,
    Zuglast AHK integer,
    Anhängerkupplung-NFZ Typ integer,
    Hintertür (Art) integer,
    Hochdach (Art) integer,
    Zustandsbericht integer,
    Mobile.de Parkungen text,
    Mobile.de Preisrating integer,
);
