name: Process Mobile.de CSV API table

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  process_table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
      - name: Commit changes (if any)
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update mobile_de_csv.json and current-table.html (if changed)'
          # Only commit if there are changes
          push: ${{ github.event.inputs.push || 'auto' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
